syntax on
filetype plugin indent on
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set number
set ruler
set relativenumber
set nowrap
set spell
set noincsearch
set nohlsearch
" This is what I use in neovim, but it doesn't work in vim?
"set guicursor n-v-sm-i:block

colorscheme industry

" Colorscheme-independent spellcheck highlighting
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=196

" Persistent undo memory
if !isdirectory($HOME."/.vim")
    call mkdir($HOME."/.vim", "", 0770)
endif
if !isdirectory($HOME."/.vim/undo")
    call mkdir($HOME."/.vim/undo", "", 0700)
endif
set undofile
set undodir=~/.vim/undo

let g:netrw_bufsettings="noma nomod nu nobl nowrap ro rnu"

let g:tex_flavor="latex"
let g:julia_indent_align_brackets=0
let g:julia_indent_align_funcargs=0

" Allow 'bracketed paste mode' when in Tmux/Screen
if &term =~ "screen" || &term =~ "tmux"
    let &t_BE = "\e[?2004h"                                              
    let &t_BD = "\e[?2004l"                                              
    let &t_PS="\e[200~"                                              
    let &t_PE="\e[201~"                                              
endif
