# Enabling and setting git info var to be used in prompt config.
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
# This line obtains information from the vcs.
zstyle ':vcs_info:git*' formats "(%b) "
precmd () { vcs_info }

# Enable substitution in the prompt.
setopt prompt_subst

# Old prompt:
#export PROMPT="%B%F{10}%n@%m %1~ %# %F{White}%b"
# Prompt with git branch:
# (change %~ to %1~ to display only the local directory name)
export PROMPT='%B%F{10}%n@%m %~ %F{White}${vcs_info_msg_0_}%F{10}%# %F{White}%b'
export GRB_LICENSE_FILE="$HOME/path/to/gurobi.lic"

# NOTE: Some juliaup-managed content goes here! 

alias gst="git status"
alias gb="git branch"
alias ga="git add"
alias gp="git pull"
alias gps="git push"
alias gm="git merge"
alias gcm="git commit -m"
alias gd="git diff"
alias gch="git checkout"

alias grep="grep --color"
